apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mtls-gateway
  namespace: default
spec:
  gatewayClassName: tigera-gateway-class
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: terminate.example.com
    tls:
      mode: Terminate
      certificateRefs:
      - name: terminate-example-tls-cert
    allowedRoutes:
      namespaces:
        from: All