## Handler timeouts & body-size
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    keep-alive: "750"
    keep-alive-requests: "1000000"
    nginx.ingress.kubernetes.io/proxy-body-size: "110m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "590"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "590"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "590"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "590"
    proxy-connect-timeout: "3600"
    proxy-read-timeout: "3600"
    upstream-keepalive-requests: "1000000"
  name: uc1-custom      
  namespace: uc1-custom
spec:
  ingressClassName: nginx
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uc1-backend
                port:
                  number: 3000