apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: namespace-iso.sticky-sess-c1-default-ns-backend
  namespace: default 
spec:
  tier: namespace-iso
  selector: app == 'backend'
  order: 500
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        namespaceSelector:
          projectcalico.org/name == 'tigera-gateway'
      destination:
        ports:
          - 3000
