# Gateway (listener)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sticky-session-gateway
  namespace: default
spec:
  gatewayClassName: tigera-gateway-class
  listeners:
  - name: uc2-http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All

