apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: keepalive-timeout-gateway
  namespace: default
spec:
  gatewayClassName: tigera-gateway-class
  listeners:
  - name: uc1-http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: uc1-https
    protocol: HTTPS
    port: 443
    hostname: "app.example.com"
    tls:
      mode: Terminate
      certificateRefs:
      - name: app-example-tls-cert # Matches the secret name
    allowedRoutes:
      namespaces:
        from: All


