---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: uc2-custom-session-affinity
  namespace: uc2-custom
spec:
  targetRefs:      # Note: Plural 'targetRefs' is the standard for recent Envoy Gateway versions
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: sticky-route # Must match the name of your HTTPRoute
  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: Cookie
      cookie:
        name: "route-cookie" # The name of the cookie Envoy will look for
        attributes:
          path: /
          sameSite: Lax
        ttl: 14400s
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sticky-route
  namespace: uc2-custom
spec:
  parentRefs:
  - name: sticky-gateway
    namespace: default
    sectionName: uc2-https
  hostnames:
  - "sticky.example.com"
  rules:
  - backendRefs:
    - name: uc2-backend
      port: 3000